# Welcome to Jekyll!
#

# Site settings
title: OMER
description: |
  Le sous-marin à propulsion humaine de l'ÉTS'  
  Club étudiant  
owner: Omerets # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: omer@ens.etsmtl.ca
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<OmerETS>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
